#!/usr/bin/python2

import argparse
import yaml

from time import time
from subprocess import call

def main():
    """Entry point for monitor"""

    parser = argparse.ArgumentParser('Monitor your component for reliability and'\
            ' uptime')


    parser.add_argument(
            '-c',
            '--conf',
            help='path to configuration file (default is'\
                    ' /etc/monitor/monitor.conf)',
            type=str,
            default='/etc/monitor/monitor.conf',
            )

    parser.add_argument(
            '-l',
            '--log',
            help='path to log file (default is'\
                    ' /var/log/monitor/monitor.log)',
            type=str,
            default='/var/log/monitor/monitor.log',
            )

    args = parser.parse_args()
    conf_path = args.conf
    log_path = args.log

    conf = read_conf(conf_path)
    probe_cmd = conf['probe']
    ret_code = call(probe_cmd, shell=True)
    current_time = int(time())

    with open(log_path,'a+') as log_f:
        log_f.write("{0}: {1}\n".format(current_time, ret_code))

    return

def read_conf(conf_path):
    """Reads the configuration file located at conf_path and returns a 
    dictionary containing the config elements of the file."""

    conf = None

    with open(conf_path,'r') as f:
        conf = yaml.load(f)
    
    return conf

if __name__ == '__main__':
    main()
